[project]
name = "simple-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "agent>=0.1.3",
    "openai>=1.68.2",
    "openai-agents>=0.0.6",
    "python-dotenv>=1.0.1",
]
